type Message {
    id: ID!
    subject: String
    body: String!
    status: MessageStatus!
    sentiment: SentimentType
    channel: Channel!
    customer: Customer
    isInbound: Boolean!
    createdAt: DateTime!
    readAt: DateTime
    repliedAt: DateTime
}

type MessageEdge {
    node: Message!
    cursor: String!
}

type MessageConnection {
    edges: [MessageEdge!]!
    pageInfo: PageInfo!
    totalCount: Int!
}

input MessageFilterInput {
    status: MessageStatus
    channelId: ID
    customerId: ID
    sentiment: SentimentType
    isInbound: Boolean
}

input CreateMessageInput {
    subject: String
    body: String!
    channelId: ID!
    customerId: ID
    isInbound: Boolean!
}
